### ISSUE TITLE
Requests to check for metarpheus latest version are not authenticated

### ISSUE THREAD

**Issue by ecamellini** [buildo/scriptoni#137]
## description

Running metarpheus could result in the following rate limit error:

![image](https://user-images.githubusercontent.com/6418684/28779240-b159e242-7602-11e7-9802-90425c37b374.png)

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs

The function to be fixed should probably be `getLatestMetarpheusFileInfo` in `scripts/metarpheus/download.js`

## misc
{optional: other useful info}

**Comment by veej** [comment]
no more download JARs!! ✌️ 
closing
