### ISSUE TITLE
transpile TS faster 🚀

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/scriptoni#150]
## requirements
https://medium.com/webpack/typescript-webpack-super-pursuit-mode-83cc568dea79

## specs
happypack or thread-loader + cache-loader?

## misc
{optional: other useful info}

**Comment by giogonzo** [comment]
Also worth noting that in the meanwhile, it should be possible to split and parallelize the tasks of typecheck and transpile, now that babel starts supporting typescript: https://github.com/Microsoft/TypeScript-Babel-Starter
