### ISSUE TITLE
Import error with default metarpheus output paths

### ISSUE THREAD

**Issue by ecamellini** [buildo/scriptoni#164]
## description

Running `metarpheus-ts` without specifying `apiOut` or `modelOut` results in the `api.ts` file importing the model from `./model-ts.ts` instead of referring to `./model.ts`. The `model-ts.ts` file does not exists, and this results in an error.

Currently fixed by adding the following to the `metarpheus-ts-config` file:

```
modelOut: 'src/metarpheus/model-ts.ts'
```

**Comment by FrancescoCioria** [comment]
fixed in a previous PR:

![image](https://user-images.githubusercontent.com/4029499/50012492-14f16180-ffbf-11e8-9cb5-35121130bfc3.png)
