### ISSUE TITLE
can we remove the "clean react" step from every build?

### ISSUE THREAD

**Issue by giogonzo** [buildo/scriptoni#169]
## description
As reported by @marcofugaro , this code is now useless and can probably be removed:
https://github.com/buildo/scriptoni/blob/3e420f862f01120e6a32c934234bfc48e826221d/bin/scriptoni.js#L24-L35

## how to reproduce
- {optional: describe steps to reproduce defect}

## specs
{optional: describe a possible fix for this defect, if not obvious}

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
YES!
