### ISSUE TITLE
Build breaks if you remove ie11 from browsers (.babelrc)

### ISSUE THREAD

**Issue by marcofugaro** [buildo/scriptoni#170]
![](https://i.imgur.com/3VdoIIT.png)

This happens because webpack3's uglify is feeded ES2015 code, and breaks since it doesn't support it.

https://github.com/buildo/scriptoni/blob/0537b837f593be57b1504ca95cd26b00cc84da5e/src/scripts/webpack/webpack.build.js#L25

## Solution 1 (Not Recommended)
Use [babel-preset-env's option `uglify`](https://babeljs.io/docs/plugins/preset-env/#targetsuglify), which transpiles everything anyway

## Solution 2 (Recommended)
Use the external [UglifyJSPlugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin), which uses uglify-es and supports ES2015 and major.

This is an example of the plugin config, it supports your current uglify config with its defaults.
```js
new UglifyJsPlugin({
  uglifyOptions: {
    ecma: 8,
    compress: {
      // Remove all console.logs
      drop_console: true,
    },
  },
  // Use multi-process parallel running to improve the build speed
  // Default number of concurrent runs: os.cpus().length - 1
  parallel: true,
  // Enable file caching
  cache: true,
}),
```

**Comment by giogonzo** [comment]
@marcofugaro good catch, thanks for reporting this! https://github.com/buildo/scriptoni/pull/171 should fix it
