### ISSUE TITLE
uglifyed build output does not work on IE11 and Chrome 38

### ISSUE THREAD

**Issue by giogonzo** [buildo/scriptoni#178]
## how to reproduce
- `NODE_ENV=production scriptoni web-build`
- `http-server build`
- run on IE11 or Chrome 38

## specs
In #170 we switched to using UglifyJS2, with a default configuration of `ecma: 8`
Apparently this setting affects both the parsed input (allow uglifying codes containing features from ecma > 5) *but also the output* (minify code *using* features of ecma 8)
Fix:
Configure UglifyJS2 to allow ecma:8 in input but output only ecma:5 compliant code:
```js
{
  ecma: 8,
  output: {
    ecma: 5
  }
}
```

## misc
It would be nice to do this based on babelrc/env (and use ecma>5 for output where possible to get a smaller output), but for the moment this seems a legit fix

/cc @marcofugaro : if you didn't notice this before probably it's because you don't need IE11 support in accurapp apps? but this config seems to have the same issue: https://github.com/accurat/accurapp/blob/aee8593966ff035cede2d8aeadbb79e7afda1695/packages/webpack-preset-accurapp/index.js#L143-L166

**Comment by marcofugaro** [comment]
@giogonzo isn't that option already set on `5` by default? 🤔 
https://github.com/mishoo/UglifyJS2/tree/harmony#output-options

Thanks for the warning! Yes, we don't support IE11 and we didn't test the code in the IE11 browser, but the uglify process at least doesn't break.

I think you might have another problem if you use some sindresohrus' dependencies which target Node 4 (and so not IE11). Those sadly need to be transpiled as well, it's a bit tricky, but if you want to check out how we do it [here it is](https://github.com/accurat/accurapp/blob/d7483afb27a3d3361acbca6f9e607e556be5c7e2/packages/webpack-preset-accurapp/index.js#L84-L90). (our most updated branch is `big-updates` for now, still haven't merged on master, sorry 🙂)

This happened to us in the past, IE11 is a bitch 😄

**Comment by giogonzo** [comment]
> @giogonzo isn't that option already set on 5 by default? 🤔
> https://github.com/mishoo/UglifyJS2/tree/harmony#output-options

It looks like but then [here](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#uglifyoptions) they say that "Supported ECMAScript Version (5, 6, 7 or 8). Affects parse, compress && output options".
I guess there's some defaulting magic done by `uglifyjs-webpack-plugin` on top of `mishoo/UglifyJS2` 🤔

**Comment by marcofugaro** [comment]
Yes probably magic 😄  thanks for the heads up! 👍
