### ISSUE TITLE
metarpheus(-diff) script does not pass all the metarpheus-io-ts options correctly

### ISSUE THREAD

**Issue by giogonzo** [buildo/scriptoni#201]
## description
In these lines https://github.com/buildo/scriptoni/blob/master/src/scripts/metarpheus/config.js#L15-L25 , we are e.g. passing `optionalType` at the top level (while `metarpheus-io-ts` expects them inside the `models` key: https://github.com/buildo/metarpheus-io-ts/blob/master/src/cli.ts#L25)

## how to reproduce
- {optional: describe steps to reproduce bug}

## specs
{optional: describe a possible fix for this bug, if not obvious}

## misc
{optional: other useful info}

**Comment by FrancescoCioria** [comment]
`optionalType` doesn't exist anymore.
(btw, metarpheus/metarpheus-diff configs in general are a complete mess and they're being fixed in #228 )
