### ISSUE TITLE
CI tests are failing with weird `SecurityError`s

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/scriptoni#213]
## description
CI tests fail with two `SecurityError`s for a misuse of `localStorage`

## how to reproduce
- https://drone.our.buildo.io/buildo/scriptoni/133

## specs
{optional: describe a possible fix for this bug, if not obvious}

## misc
{optional: other useful info}

**Comment by giogonzo** [comment]
closed by ccd8be5f1ffaa00b196b73acfa17f654a94895f8
