### ISSUE TITLE
devtool/sourceMap: remove? 

### ISSUE THREAD

**Issue by giogonzo** [buildo/scriptoni#224]
## description
`sourceMap` is set in many different parts of the configuration:

![image](https://user-images.githubusercontent.com/6418684/46530025-cd50aa00-c898-11e8-9955-adf9756c49d7.png)

Is it necessary? Isn't retrieved/overridden by the root Webpack configuration?

**Comment by FrancescoCioria** [comment]
nope:
- first one is from tsconfig => unrelated
- second one is used in `UglifyJsPlugin` which is `build` only
- 3,4 and 5 are used in the sass module of the `build` config which is defined here, not in `base`
- 6 is used in the sass module of the `dev` config which is defined here, not in `base` (too different from `build`)
