### ISSUE TITLE
Add webpack typescript scripts

### ISSUE THREAD

**Issue by ascariandrea** [buildo/scriptoni#91]
## requirements
As an experiment on a few projects (1 for the moment), we want to use webpack+TS as instead of webpack+babel.
This repo should support both options in some way

## specs
- use `awesome-typescript-loader` instead of `babel-loader`
- update require extensions to include `.ts` and `.tsx`

## misc
`typo` branch in `aliniq` shows how this should be done

**Comment by giogonzo** [comment]
@ascariandrea this is a [WIP branch](https://github.com/buildo/scriptoni/commit/7be4d34292db69dbf31a6163ccf9d8202260b386), if you have any comment
